AGTEF_2.1.0

diff --git a/etc/init.d/ngwfdd b/etc/init.d/ngwfdd
--- a/etc/init.d/ngwfdd
+++ b/etc/init.d/ngwfdd
@@ -5,20 +5,141 @@ USE_PROCD=1
 LOGTAG="ngwfdd"
 
 start_service_instance() {
-    procd_open_instance "$1"
+    local SERVICE="$1"
+    if [ "$SERVICE" = "pgroup" ]; then
+      SERVICE="$2"
+    fi
+    procd_open_instance "${SERVICE}"
     procd_set_param command "$@"
     procd_set_param respawn
     procd_set_param stderr 1
     procd_close_instance
 }
 
-start_service() {
-    . $IPKG_INSTROOT/lib/functions.sh
+set_url() {
+    local ACTION_DEFAULT=$(uci_get system @$1[0] action_default '')
+    local ACTION=$(uci_get system @$1[0] action '')
 
+    if [ -z "${ACTION_DEFAULT}" -a -n "${ACTION}" ]; then
+        uci_set system @$1[0] action_default ${ACTION}
+    fi
+    uci_set system @$1[0] url "$2"
+    uci_set system @$1[0] action upload
+    uci_commit system @$1[0]
+}
+
+add_custom_http_header() {
+  local HDR="$1"
+  local config="$2"
+  echo "header = $HDR" >>$config
+}
+
+create_config() {
+  local config="$1"
+  local URL
+  config_get URL config base_url
+  if [ -z "${URL}" ]; then
+      logger -t "$LOGTAG" "ngwfdd.config.base_url is not configured properly = '${URL}'"
+      return 1
+  fi
+
+  local FIFO_DIR
+  config_get FIFO_DIR config fifo_dir '/tmp/gwfd'
+  if ! mkdir -p "${FIFO_DIR}"; then
+      logger -t "$LOGTAG" "Invalid fifo directory 'ngwfdd.config.fifo_dir = ${FIFO_DIR}'"
+      return 1
+  fi
+
+  echo "base_url = $URL" > $config
+  echo "fifo_dir = $FIFO_DIR" >> $config
+
+  local REQPATH
+  config_get REQPATH config url_path
+  [ -n "$REQPATH" ] && echo "url_path = $REQPATH" >>$config
+  config_list_foreach config headers add_custom_http_header "$config"
+
+  local FLUSH_SIZE
+  config_get FLUSH_SIZE config flush_size 100
+  echo "flush_size = $FLUSH_SIZE" >> $config
+
+  local FLUSH_INTERVAL
+  config_get FLUSH_INTERVAL config flush_interval 10
+  echo "flush_interval = $FLUSH_INTERVAL" >> $config
+
+  local TAG
+  config_get TAG config tag
+  [ -n "$TAG" ] && echo "tag = $TAG" >> $config
+
+  local SERIAL="$(uci_get env rip factory_id)$(uci_get env rip serial)"
+  echo "serial_nr = $SERIAL" >> $config
+
+  local BOARD="$(uci_get env rip board_mnemonic)"
+  echo "board_name = $BOARD" >> $config
+
+  local VERSION="$(uci_get version @version[0] version | cut -d- -f1)"
+  echo "firmware_version = $VERSION" >> $config
+
+  echo $FIFO_DIR
+}
+
+create_piddir() {
+    local PIDDIR=/var/run/ngwfdd
+    mkdir -p $PIDDIR
+    echo $PIDDIR
+}
+
+start_collectors() {
+    local DIR="$1"
+    local FIFO_DIR="$2"
+    local DEFAULT_ENABLE=${3:-1}
+    local PIDDIR=$(create_piddir)
+
+    local SERVICE FIFO MODULE PIDFILE INTERVAL
+
+    for SERVICE in $DIR/mod_*.lua; do
+        if [ -x "${SERVICE}" ]; then
+            MODULE=$(basename "${SERVICE}" .lua | cut -d_ -f2-)
+            config_get_bool ENABLE enabled ${MODULE} ${DEFAULT_ENABLE}
+            config_get INTERVAL interval ${MODULE} none
+            if [ "${ENABLE}" != "0" ]; then
+                FIFO="${FIFO_DIR}/${MODULE}"
+                if [ ! -p "${FIFO}" ]; then
+                    rm -rf "${FIFO}"
+                    mkfifo "${FIFO}"
+                fi
+                PIDFILE=$PIDDIR/$MODULE
+                logger -t "$LOGTAG" "Starting ${SERVICE} service"
+                start_service_instance pgroup "${SERVICE}" "$PIDFILE" "${FIFO}" "${INTERVAL}"
+            fi
+        fi
+    done
+}
+
+stop_collectors() {
+    local DIR="$1"
+    local FIFO_DIR="$2"
+    local PIDDIR=$(create_piddir)
+
+    local SERVICE MODULE PIDFILE PID
+    for SERVICE in $DIR/mod_*.lua; do
+        MODULE=$(basename "${SERVICE}" .lua | cut -d_ -f2)
+        PIDFILE=$PIDDIR/$MODULE
+        PID=$(cat $PIDFILE 2>/dev/null)
+        [ -n "${PID}" ] && kill -TERM -${PID}
+        FIFO=${FIFO_DIR}/${MODULE}
+        rm -rf $FIFO
+        rm -rf $PIDFILE
+    done
+}
+
+start_service() {
+    local CONFIG=/var/run/ngwfdd.config
+    mkdir -p $(dirname $CONFIG)
+
+    /usr/lib/ngwfdd/sanitize_config
     config_load ngwfdd
 
-    local ENABLE STORED_VERSION BASE_URL FIFO_DIR CORE_URL SERIAL_CFG SERIAL BOARD_CFG BOARD VERSION_CFG VERSION SERVICE FIFO_NAME
-
+    local ENABLE
     config_get_bool ENABLE config enable 0
     if [ "${ENABLE}" != "1" ]; then
         logger -t "$LOGTAG" "Field Diagnostics Daemon disabled"
@@ -26,91 +147,30 @@ start_service() {
     fi
 
     if [ ! -x /usr/share/ngwfdd ] ; then
+        logger -t "${LOGTAG}" "Field Diagnostics Deamon not found"
         return 1
     fi
 
-    local OWN_VERSION="$(opkg info ngwfdd | grep Version | cut -d: -f2 | tr -d ' ')"
-    config_get STORED_VERSION config ngwfdd_version
-    if [ "${OWN_VERSION}" != "${STORED_VERSION}" ]; then
-        uci_set ngwfdd config ngwfdd_version "${OWN_VERSION}"
-        uci_commit ngwfdd config
-    fi
-
-    config_get BASE_URL config base_url
-    if [ -z "${BASE_URL}" ]; then
-        logger -t "$LOGTAG" "ngwfdd.config.base_url is not configured properly = '${BASE_URL}'"
-        return 1
-    fi
-
-    config_get FIFO_DIR config fifo_dir '/tmp/gwfd'
-    if ! mkdir -p "${FIFO_DIR}"; then
-        logger -t "$LOGTAG" "Invalid fifo directory 'ngwfdd.config.fifo_dir = ${FIFO_DIR}'"
-        return 1
-    fi
+    local FIFO_DIR
+    FIFO_DIR=$(create_config $CONFIG) || return 1
 
     config_get CORE_URL config core_url
     #If a coredump URL is set, we will overwrite the default system url
     if [ -n "${CORE_URL}" ]; then
-        uci_set system @coredump[0] url "${CORE_URL}"
-        uci_set system @coredump[0] action upload
-        uci_set system @kernel_crash[0] url "${CORE_URL}"
-        uci_set system @kernel_crash[0] action upload
-        uci_commit system @coredump[0]
+        set_url "coredump" "${CORE_URL}"
+        set_url "kernel_crash" "${CORE_URL}"
     fi
 
-    config_get SERIAL_CFG config serial_nr
-    local SERIAL="$(uci_get env rip factory_id)$(uci_get env rip serial)"
-    if [ -z "${SERIAL_CFG}" ] || [ "${SERIAL_CFG}" != "${SERIAL}" ]; then
-        uci_set ngwfdd config serial_nr "${SERIAL}"
-        uci_commit ngwfdd config
-    fi
-
-    config_get BOARD_CFG config board_name
-    BOARD="$(uci_get env rip board_mnemonic)"
-    if [ -z "${BOARD_CFG}" ] || [ "${BOARD_CFG}" != "${BOARD}" ]; then
-        uci_set ngwfdd config board_name "${BOARD}"
-        uci_commit ngwfdd config
-    fi
-
-    config_get VERSION_CFG config firmware_version
-    VERSION="$(uci_get version @version[0] version | cut -d- -f1)"
-    if [ -z "${VERSION_CFG}" ] || [ "${VERSION_CFG}" != "${VERSION}" ]; then
-        uci_set ngwfdd config firmware_version "${VERSION}"
-        uci_commit ngwfdd config
-    fi
-
-    for SERVICE in /usr/share/ngwfdd/mod_*.lua; do
-        FIFO_NAME=$(basename "${SERVICE}" .lua | cut -c5-)
-        FIFO_NAME="${FIFO_DIR}/${FIFO_NAME}"
-        if [ ! -p "${FIFO_NAME}" ]; then
-            rm -rf "${FIFO_NAME}"
-            mkfifo "${FIFO_NAME}"
-        fi
-        logger -t "$LOGTAG" "Starting ${SERVICE} service"
-        start_service_instance "${SERVICE}" "${FIFO_NAME}"
-    done
+    start_collectors /usr/share/ngwfdd $FIFO_DIR 1
+    start_collectors /opt/usr/share/ngwfdd $FIFO_DIR 0
 
     logger -t "$LOGTAG" "Starting ngwfdd"
-    start_service_instance /usr/bin/ngwfdd
+    start_service_instance /usr/bin/ngwfdd --config $CONFIG --pidfile /var/run/ngwfdd.pid
 }
 
 stop_service() {
     local FIFO_DIR="$(uci_get ngwfdd config fifo_dir '/tmp/gwfd')"
-    for SERVICE in /usr/share/ngwfdd/*.lua; do
-        local SERVICE_PID="$(pgrep -f -n "$SERVICE")"
-        if [ -n "$SERVICE_PID" ]; then
-            local CHILD_PIDS="$(pgrep -P "$SERVICE_PID")"
-            for CPID in $CHILD_PIDS; do
-                local GRANDCHILD_PIDS="$(pgrep -P "$CPID")"
-                for GCPID in $GRANDCHILD_PIDS; do
-                    logger -t "$LOGTAG" "Killing grandchild process $GCPID"
-                    kill "$GCPID"
-                done
-                logger -t "$LOGTAG" "Killing child process $CPID"
-                kill "$CPID"
-            done
-        fi
-        local FIFO_NAME="$(basename "${SERVICE}" .lua | cut -c5-)"
-        rm -f "${FIFO_DIR}/${FIFO_NAME}"
-    done
+    stop_collectors /usr/share/ngwfdd $FIFO_DIR
+    stop_collectors /opt/usr/share/ngwfdd $FIFO_DIR
+    rm /var/run/ngwfdd.pid
 }
diff --git a/sbin/kernel-panic-handler b/sbin/kernel-panic-handler
--- a/sbin/kernel-panic-handler
+++ b/sbin/kernel-panic-handler
@@ -8,6 +8,7 @@ log() {
 
 action="$(uci_get system @kernel_crash[0] action nocore)"
 path="$(uci_get system @kernel_crash[0] path /tmp)"
+ngwfdd_state="$(uci_get ngwfdd config enable)"
 
 clear_prozone=1
 filename="kernel_crash"
@@ -19,45 +20,46 @@ cat "/proc/prozone/panic" > "$tmpfile"
 	exit 0
 }
 
-case "${action}" in
-	compress)
-		log "kernel panic info dumped to ${path}/${filename}.gz"
-		gzip -c "$tmpfile" > "${path}/${filename}.gz"
-	;;
-	store)
-		log "kernel panic info dumped to ${path}/${filename}"
-		cp "$tmpfile" "${path}/${filename}"
-	;;
-	upload)
-		url="$(uci_get system @kernel_crash[0] url)"
-		if [ -n "${url}" ]; then
-			version="$(uci_get version @version[0] version unknown)"
-			factory_id="$(uci_get env rip factory_id unknown)"
-			board="$(uci_get env rip board_mnemonic unknown)"
-			oid="$(uci_get version @version[0] oid unknown)"
-			serial="$(uci_get env rip serial unknown)"
+if [ "$ngwfddState" == "1" ] then
+	case "${action}" in
+		compress)
+			log "kernel panic info dumped to ${path}/${filename}.gz"
+			gzip -c "$tmpfile" > "${path}/${filename}.gz"
+		;;
+		store)
+			log "kernel panic info dumped to ${path}/${filename}"
+			cp "$tmpfile" "${path}/${filename}"
+		;;
+		upload)
+			url="$(uci_get system @kernel_crash[0] url)"
+			if [ -n "${url}" ]; then
+				version="$(uci_get version @version[0] version unknown)"
+				factory_id="$(uci_get env rip factory_id unknown)"
+				board="$(uci_get env rip board_mnemonic unknown)"
+				oid="$(uci_get version @version[0] oid unknown)"
+				serial="$(uci_get env rip serial unknown)"
 
-			# Insert the ngwfdd tag when uploading to Kibana
-			[ "$(uci_get ngwfdd config enable)" = "1" -a "$url" = "$(uci_get ngwfdd config core_url)" ] && tag="$(uci_get ngwfdd config tag)"
+				# Insert the ngwfdd tag when uploading to Kibana
+				[ "$(uci_get ngwfdd config enable)" = "1" -a "$url" = "$(uci_get ngwfdd config core_url)" ] && tag="$(uci_get ngwfdd config tag)"
 
-			log "uploading kernel panic info to ${url}"
-			if ! curl -m 360 -X POST -F "exe=kernel_panic" -F "version=${version}" -F "oid=${oid}" -F "serial=${factory_id}${serial}" -F "board=${board}" -F "file=@$tmpfile" ${tag:+-F tag="$tag"} "${url}"; then
-				log "failed to upload kernel panic info"
-				clear_prozone=0
+				log "uploading kernel panic info to ${url}"
+				if ! curl -m 360 -X POST -F "exe=kernel_panic" -F "version=${version}" -F "oid=${oid}" -F "serial=${factory_id}${serial}" -F "board=${board}" -F "file=@$tmpfile" ${tag:+-F tag="$tag"} "${url}"; then
+					log "failed to upload kernel panic info"
+					clear_prozone=0
+				else
+					log "kernel panic info uploaded"
+				fi
 			else
-				log "kernel panic info uploaded"
+				log "invalid kernel panic info upload url"
+				clear_prozone=0
 			fi
-		else
-			log "invalid kernel panic info upload url"
+		;;
+		*)
+			log "unknown kernel panic info action"
 			clear_prozone=0
-		fi
-	;;
-	*)
-		log "unknown kernel panic info action"
-		clear_prozone=0
-	;;
-esac
-
+		;;
+	esac
+fi
 rm -rf "$tmpfile"
 
 if [ "$clear_prozone" = "1" ]; then
