AGTEF_2.1.0_001

diff --git a/etc/init.d/ngwfdd b/etc/init.d/ngwfdd
--- a/etc/init.d/ngwfdd
+++ b/etc/init.d/ngwfdd
@@ -1,160 +1,116 @@
 #!/bin/sh /etc/rc.common
 
 START=99
-SERVICE_DAEMONIZE=1
-SERVICE_WRITE_PID=1
-unset SERVICE_MATCH_EXEC
+USE_PROCD=1
+LOGTAG="ngwfdd"
 
-local_check_old_config() {
-    #If an old action was defined restore it.
-    OLD_ACTION="$(uci get ngwfdd.config.old_action 2> /dev/null)"
-    OLD_URL="$(uci get ngwfdd.config.old_url 2> /dev/null)"
-    if [ -n "${OLD_ACTION}" ]; then
-        uci set system.@coredump[0].action=${OLD_ACTION}
-        uci set ngwfdd.config.old_action=""
-        #OLD_URL can be an empty string. If it is, then the original url was also empty
-        #We set the values.
-        uci set system.@coredump[0].url=${OLD_URL}
-        uci set ngwfdd.config.old_url=""
-        uci commit system.@coredump[0]
-        uci commit ngwfdd.config
-    fi
+start_service_instance() {
+    procd_open_instance "$1"
+    procd_set_param command "$@"
+    procd_set_param respawn
+    procd_set_param stderr 1
+    procd_close_instance
 }
 
-local_safe_start_service() {
-    service_check $1 2> /dev/null
-    if [ "$?" = "0" ]; then
-        echo "$1 is already running ..."
-    else
-        service_start $@
-    fi
-}
+start_service() {
+    . $IPKG_INSTROOT/lib/functions.sh
 
-start() {
-    ENABLE="$(uci get ngwfdd.config.enable 2> /dev/null)"
+    config_load ngwfdd
+
+    local ENABLE STORED_VERSION BASE_URL FIFO_DIR CORE_URL SERIAL_CFG SERIAL BOARD_CFG BOARD VERSION_CFG VERSION SERVICE FIFO_NAME
+
+    config_get_bool ENABLE config enable 0
     if [ "${ENABLE}" != "1" ]; then
-        #If an old action was defined restore it.
-        local_check_old_config
-        exit 0
-    fi
-
-    OWN_VERSION="$(opkg info ngwfdd | grep Version | cut -d: -f2 | tr -d ' ')"
-    STORED_VERSION="$(uci get ngwfdd.config.ngwfdd_version 2> /dev/null)"
-    if [ "${OWN_VERSION}" != "${STORED_VERSION}" ]; then
-        uci set ngwfdd.config.ngwfdd_version="${OWN_VERSION}"
-        uci commit ngwfdd.config
-    fi
-
-    #Configuration check; Make sure all parameters are set.
-    BASE_URL="$(uci get ngwfdd.config.base_url 2> /dev/null)"
-    if [ -z "${BASE_URL}" -o "xhttps" != "$(echo x${BASE_URL} | cut -d: -f1 )" ]; then
-        echo "ngwfdd.config.base_url is not configured properly = '${BASE_URL}'"
-        exit 1
-    fi
-
-    FIFO_DIR="$(uci get ngwfdd.config.fifo_dir)"
-    if [ -z "${FIFO_DIR}" ]; then
-        echo "ngwfdd.config.fifo_dir is not set"
-        exit 1
-    fi
-
-    if [ ! -e ${FIFO_DIR} ]; then
-        mkdir -p ${FIFO_DIR}
-        if [ "$?" != "0" ]; then
-            exit 1
-        fi
-    else
-        #Fifo dir exists. It must be a directory.
-        if [ ! -d ${FIFO_DIR} ]; then
-            echo "ngwfdd.config.fifo_dir(='${FIFO_DIR}') exists, but is not a directory."
-            exit 1
-        fi
+        logger -t "$LOGTAG" "Field Diagnostics Daemon disabled"
+        return 0
     fi
 
     if [ ! -x /usr/share/ngwfdd ] ; then
-        exit 1
+        return 1
     fi
 
-    CORE_URL="$(uci get ngwfdd.config.core_url 2> /dev/null)"
-    #An empty core URL is allowed. The existing crash config will be used.
+    local OWN_VERSION="$(opkg info ngwfdd | grep Version | cut -d: -f2 | tr -d ' ')"
+    config_get STORED_VERSION config ngwfdd_version
+    if [ "${OWN_VERSION}" != "${STORED_VERSION}" ]; then
+        uci_set ngwfdd config ngwfdd_version "${OWN_VERSION}"
+        uci_commit ngwfdd config
+    fi
+
+    config_get BASE_URL config base_url
+    if [ -z "${BASE_URL}" ]; then
+        logger -t "$LOGTAG" "ngwfdd.config.base_url is not configured properly = '${BASE_URL}'"
+        return 1
+    fi
+
+    config_get FIFO_DIR config fifo_dir '/tmp/gwfd'
+    if ! mkdir -p "${FIFO_DIR}"; then
+        logger -t "$LOGTAG" "Invalid fifo directory 'ngwfdd.config.fifo_dir = ${FIFO_DIR}'"
+        return 1
+    fi
+
+    config_get CORE_URL config core_url
+    #If a coredump URL is set, we will overwrite the default system url
     if [ -n "${CORE_URL}" ]; then
-        #First check if we have a valid URL
-        if [  "xhttps" != "$(echo x${CORE_URL} | cut -d: -f1 )" ]; then
-            echo "ngwfdd.config.core_url is not configured properly = '${CORE_URL}'"
-            exit 1
+        uci_set system @coredump[0] url "${CORE_URL}"
+        uci_set system @coredump[0] action upload
+        uci_set system @kernel_crash[0] url "${CORE_URL}"
+        uci_set system @kernel_crash[0] action upload
+        uci_commit system @coredump[0]
+    fi
+
+    config_get SERIAL_CFG config serial_nr
+    local SERIAL="$(uci_get env rip factory_id)$(uci_get env rip serial)"
+    if [ -z "${SERIAL_CFG}" ] || [ "${SERIAL_CFG}" != "${SERIAL}" ]; then
+        uci_set ngwfdd config serial_nr "${SERIAL}"
+        uci_commit ngwfdd config
+    fi
+
+    config_get BOARD_CFG config board_name
+    BOARD="$(uci_get env rip board_mnemonic)"
+    if [ -z "${BOARD_CFG}" ] || [ "${BOARD_CFG}" != "${BOARD}" ]; then
+        uci_set ngwfdd config board_name "${BOARD}"
+        uci_commit ngwfdd config
+    fi
+
+    config_get VERSION_CFG config firmware_version
+    VERSION="$(uci_get version @version[0] version | cut -d- -f1)"
+    if [ -z "${VERSION_CFG}" ] || [ "${VERSION_CFG}" != "${VERSION}" ]; then
+        uci_set ngwfdd config firmware_version "${VERSION}"
+        uci_commit ngwfdd config
+    fi
+
+    for SERVICE in /usr/share/ngwfdd/mod_*.lua; do
+        FIFO_NAME=$(basename "${SERVICE}" .lua | cut -c5-)
+        FIFO_NAME="${FIFO_DIR}/${FIFO_NAME}"
+        if [ ! -p "${FIFO_NAME}" ]; then
+            rm -rf "${FIFO_NAME}"
+            mkfifo "${FIFO_NAME}"
         fi
-        #Check if we need to back-up the current coredump config.
-        OLD_ACTION="$(uci get ngwfdd.config.old_action 2> /dev/null)"
-        if [ -z "${OLD_ACTION}" ]; then
-            #only store the old config, if we haven't done it.
-            ACTION="$(uci get system.@coredump[0].action)"
-            URL="$(uci get system.@coredump[0].url 2> /dev/null)"
-            uci set ngwfdd.config.old_action="${ACTION}"
-            uci set ngwfdd.config.old_url="${URL}"
-            uci commit ngwfdd.config
-        fi
-        uci set system.@coredump[0].url=${CORE_URL}
-        uci set system.@coredump[0].action=upload
-        uci commit system.@coredump[0]
-    fi
-
-    #Fill optional parameters if needed.
-    SERIAL_CFG="$(uci get ngwfdd.config.serial_nr 2> /dev/null)"
-    SERIAL="$(uci get env.rip.factory_id)$(uci get env.rip.serial)"
-    if [ -z "${SERIAL_CFG}" -o "${SERIAL_CFG}" != "${SERIAL}" ]; then
-        uci set ngwfdd.config.serial_nr="${SERIAL}"
-        uci commit ngwfdd.config
-    fi
-
-    BOARD_CFG="$(uci get ngwfdd.config.board_name 2> /dev/null)"
-    BOARD="$(uci get env.rip.board_mnemonic)"
-    if [ -z "${BOARD_CFG}" -o "${BOARD_CFG}" != "${BOARD}" ]; then
-        uci set ngwfdd.config.board_name="${BOARD}"
-        uci commit ngwfdd.config
-    fi
-
-    VERSION_CFG="$(uci get ngwfdd.config.firmware_version 2> /dev/null)"
-    VERSION="$(uci get version.@version[0].version | cut -d- -f1)"
-    if [ -z "${VERSION_CFG}" -o "${VERSION_CFG}" != "${VERSION}" ]; then
-        uci set ngwfdd.config.firmware_version="${VERSION}"
-        uci commit ngwfdd.config
-    fi
-
-    for x in $(ls /usr/share/ngwfdd/mod_*.lua) ; do
-        name=$(basename "${x}" .lua | cut -c5-)
-        fifo="${FIFO_DIR}/${name}"
-        if [ ! -p ${fifo} ];then
-            rm -rf ${fifo} || true
-            mkfifo ${fifo}
-        fi
-        echo "starting lua service ${x}"
-        local_safe_start_service ${x} ${fifo}
+        logger -t "$LOGTAG" "Starting ${SERVICE} service"
+        start_service_instance "${SERVICE}" "${FIFO_NAME}"
     done
 
-    echo "starting ngwfdd..."
-    local_safe_start_service /usr/bin/ngwfdd
+    logger -t "$LOGTAG" "Starting ngwfdd"
+    start_service_instance /usr/bin/ngwfdd
 }
 
-stop() {
-    local_check_old_config
-    #Following part takes care of stopping the logread -f process generated by /usr/share/ngwfdd/mod_syslog
-    pids=$(ps w|grep -v 'grep'|grep mod_syslog| awk '{print $1}')
-    logreadpids=$(ps |grep -v 'grep'|grep 'logread -f'| awk '{print $1}')
-    pgrpid=$(cat /proc/${pids}/stat|cut -d' ' -f5)
-    for lpid in ${logreadpids}; do
-        Lpgrpid=$(cat /proc/${lpid}/stat|cut -d' ' -f5)
-        if [ $Lpgrpid = $pgrpid ]; then
-            kill -9 $lpid
+stop_service() {
+    local FIFO_DIR="$(uci_get ngwfdd config fifo_dir '/tmp/gwfd')"
+    for SERVICE in /usr/share/ngwfdd/*.lua; do
+        local SERVICE_PID="$(pgrep -f -n "$SERVICE")"
+        if [ -n "$SERVICE_PID" ]; then
+            local CHILD_PIDS="$(pgrep -P "$SERVICE_PID")"
+            for CPID in $CHILD_PIDS; do
+                local GRANDCHILD_PIDS="$(pgrep -P "$CPID")"
+                for GCPID in $GRANDCHILD_PIDS; do
+                    logger -t "$LOGTAG" "Killing grandchild process $GCPID"
+                    kill "$GCPID"
+                done
+                logger -t "$LOGTAG" "Killing child process $CPID"
+                kill "$CPID"
+            done
         fi
+        local FIFO_NAME="$(basename "${SERVICE}" .lua | cut -c5-)"
+        rm -f "${FIFO_DIR}/${FIFO_NAME}"
     done
-
-    FIFO_DIR="$(uci get ngwfdd.config.fifo_dir)"
-    for x in $(ls /usr/share/ngwfdd/*.lua) ; do
-        service_stop ${x} 2> /dev/null
-        name=$(basename "${x}" .lua | cut -c5-)
-        rm -f "${FIFO_DIR}/${name}"
-    done
-
-    service_stop /usr/bin/ngwfdd 2> /dev/null
 }
-
diff --git a/etc/init.d/wifi-doctor-agent b/etc/init.d/wifi-doctor-agent
--- a/etc/init.d/wifi-doctor-agent
+++ b/etc/init.d/wifi-doctor-agent
@@ -4,16 +4,21 @@ START=99
 STOP=10
 USE_PROCD=1
 
-. /lib/functions.sh
+. ${IPKG_INSTROOT}/lib/functions.sh
 
-set_default_acs() {
+set_default_acs()
+{
   local radio=$1
+  local ubus_call
   local acs_list
+  local chan_list
+  local list
   config_load "wireless"
   config_get acs_list $radio acs_allowed_channels
   if [ -z "$acs_list" ]
   then
     # list is empty, try UBUS
+    # We need the intersect of .radio and .radio.acs (see NG-177126)
     ubus_call="ubus call wireless.radio.acs get '{ \"name\" : \"$radio\" }' | grep allowed_channels"
     acs_list="`eval $ubus_call`"
     if [ $? != 0 ]
@@ -21,7 +26,20 @@ set_default_acs() {
        logger -t "wifi-doctor-agent" "[procd setting defaults]: $radio - UBUS returned error"
        return
     fi
-    acs_list="`echo $acs_list | sed "s/[^0-9 ]//g" `"
+
+    ubus_call="ubus call wireless.radio get '{ \"name\" : \"$radio\" }' | grep allowed_channels"
+    chan_list="`eval $ubus_call`"
+    if [ $? != 0 ]
+    then
+       logger -t "wifi-doctor-agent" "[procd setting defaults]: $radio - UBUS returned error"
+       return
+    fi
+
+    # Calculate the intersect of both lists
+    # Note the itteration 1 - 200 is crude, but limited AWK functionality on OWA ...
+    # This limits the channel range from 1 .. 200 which should be OK.
+    list="`echo $acs_list $chan_list | sed "s/[^0-9 ]//g" `"
+    acs_list=`echo "${list} " | awk 'BEGIN {RS=" "; ORS=" "} { cnts[$0] += 1} END { for ( i=1 ; i < 200 ; i++ ) if (cnts[i] > 1 ) print i }'`
     if [ ${#acs_list} -lt 2 ] # Check that there is at least one channel in the list (has a leading ' ')
     then
       logger -t "wifi-doctor-agent" "[procd setting defaults]: $radio - empty ACS list"
diff --git a/usr/bin/sysupgrade-safe b/usr/bin/sysupgrade-safe
--- a/usr/bin/sysupgrade-safe
+++ b/usr/bin/sysupgrade-safe
@@ -6,17 +6,17 @@ GUI_OPTION=
 
 # parse options
 while [ -n "$1" ]; do
-        case "$1" in
-                -S|--skip-signature) SKIP_SIGNATURE=1;;
-                -o) REBOOT_OPTION="-o -s";;
-                --gui) GUI_OPTION=--gui;;
-                -*)
-                        echo "Invalid option: $1"
-                        exit 1
-                ;;
-                *) break;;
-        esac
-        shift;
+	case "$1" in
+		-S|--skip-signature) SKIP_SIGNATURE=1;;
+		-o) REBOOT_OPTION="-o -s";;
+		--gui) GUI_OPTION=--gui;;
+		-*)
+			echo "Invalid option: $1"
+			exit 1
+		;;
+		*) break;;
+	esac
+	shift;
 done
 
 UPGRADE_URL="$1"
@@ -39,12 +39,12 @@ fi
 
 sysupgrade --safe ${REBOOT_OPTION} ${GUI_OPTION} ${SIGNATURE_OPTION} "${UPGRADE_URL}"
 
-if [ $? -ne 0 ]                          
-then                           
-        if [ -f /tmp/getimageerr ];              
-        then                   
-                rm -rf /tmp/getimageerr
-                exit 1    
-        fi     
-        exit 2 
-fi             
+if [ $? -ne 0 ]
+then
+	if [ -f /tmp/getimageerr ];
+	then
+		rm -rf /tmp/getimageerr
+		exit 1
+	fi
+	exit 2
+fi
